---
name: Lint

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    - name: Reformat code base
      run: find . -type f -name '*.go' -exec go fmt {} \;
    - name: Stop if reformatted
      run: git diff --exit-code
