---
name: Test

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    - uses: actions/cache@v2
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Run test suite
      run: make test
